name: Validate Renovate presets

on:
  pull_request:
    paths:
      - "default.json"
      - ".github/workflows/validate.yml"
  workflow_dispatch:

permissions: {}

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - run: |
          for config in default.json preset.json5; do
            docker run --rm -v \
              "${{ github.workspace }}:/workspace" \
              -w /workspace \
              ghcr.io/renovatebot/renovate:latest \
              renovate-config-validator \
              "$config"
          done
